title: JUST DO IT!
description: Research Blog with Paper Reviews
author: Sanghyuk Lee
thumbnail: /assets/img/coast.jpg

url: https://shlee625.github.io
paginate_path: "/posts/page:num/"
permalink: /posts/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Posts
    url: /posts
  - title: Archives
    url: /archives

social:
  github: shlee625
  twitter: 
  facebook: 
  email: sanghyuk.lee625@gmail.com
  linkedin: sanghyuklee625

google_analytics: "UA-58263416-1"

disqus:
    shortname: sanghyuk lee